### ISSUE TITLE
réécriture htaccess

### ISSUE THREAD

**Issue by Moldjuice** [axessweb/projet-base-W#1]
Salut axessweb ;-)

Juste pour info, il semble que la réécriture qui renvoi à public/index.php soit la cause d'un code 404 généré par apache au sein de l'entête http. Ce qui pourrait créer un problème d'ordre SEO pour la page d'accueil (les autre pages ne sont pas impactées par ce problème).

**fichier**
public/.htaccess

**Probable ligne en cause**
`Réécrit tout le reste à public/index.php.`
`RewriteRule .? %{ENV:W_BASE}/index.php [L]`

Une idée ?

Merci, à bientôt ;-)

**Comment by axessweb** [comment]
Salut,

Rentre dans ton dossier... et "composer update". Ca devrait fonctionner
plutôt pas mal.
W est en version 1.2 (un bug subsistait sur la 1.1).

Par défaut, le projet base charge la 1.2, je vais changer ça rapidement.


Sinon ça roule ?

Axel Wargnier
Tél: 06.52.75.77.07


Le mer. 27 févr. 2019 à 01:28, Moldjuice <notifications@github.com> a
écrit :

**Comment by axessweb** [comment]
Salut, 

Rentre dans ton dossier du projet... et "composer update".

Ca devrait fonctionner plutôt pas mal. 

W est passé en version 1.2 (un bug subsistait sur la 1.1). 

Par défaut, le projet base charge la 1.1. je vais changer ça rapidement.

**Comment by axessweb** [comment]
Fixed in commit 81148179a215ec240b0a1fe835ebdc7cabe9661e

**Comment by Moldjuice** [comment]
Hello, 
Merci pour ta réactivité ;-) 
J'ai mis à jour le projet mais une erreur suite à la maj 1.1.3 -> 1.2.1

`Fatal error: Cannot use Psr\Http\Message\UriInterface as UriInterface because the name is already in use in E:\apps\wamp64\www\mon-projet\vendor\league\uri-manipulations\src\functions.php on line 19`

Cela semble lié à l'install de league/uri-manipulations.

Détail de l'update : 

 - Removing true/punycode (v2.1.1)
 - Removing symfony/polyfill-mbstring (v1.8.0)
 - Removing league/url (3.3.5)
 - Updating phpmailer/phpmailer (v6.0.5 => v6.0.7): Downloading (100%)
 - Installing league/uri-interfaces (1.1.1): Downloading (100%)
 - Installing league/uri-parser (1.4.1): Downloading (100%)
 - Installing psr/http-message (1.0.1): Downloading (100%)
 - Installing league/uri-schemes (1.2.1): Downloading (100%)
 - Installing psr/simple-cache (1.0.1): Downloading (100%)
 - Installing league/uri-hostname-parser (1.1.1): Downloading (100%)
 - Installing league/uri-components (1.8.2): Downloading (100%)
 - Installing league/uri-manipulations (1.5.0): Downloading (100%)
 - Updating webforce3/w (1.1 => 1.2.2): Downloading (100%)
 - Updating google/recaptcha (1.1.3 => 1.2.1): Downloading (100%)

Tu aurais une piste stp ?

**Comment by axessweb** [comment]
Un composer update ?

**Comment by Moldjuice** [comment]
Oui j'ai lancé un "composer update" au sein de mon projet.

**Comment by Moldjuice** [comment]
Ok, je viens de voir que la version de W n'était plus compatible avec ma version de PHP (7.0.10) 

"PHP: >= 7.0.13"

Je suis donc passé en 7.2.5 et une autre erreur survient liée la redéclaration de la méthode getApp(). J'utilise pas mal getApp() car je stocke beaucoup d'infos liées au projet sur mon fichier config. j'espère que ce n'est pas un souci avec la nouvelle version ... je continu de regarder.

`Fatal error: Cannot redeclare getApp() (previously declared in E:\apps\wamp64\www\mon-projet\vendor\webforce3\w\W\globals.php:21) in E:\apps\wamp64\www\mon-projet\vendor\webforce3\w\W\globals.php on line 21`

**Comment by axessweb** [comment]
Aucun souci avec getApp(), qui continue d'exister pour justement récupérer le fichier de config (entre autre).

Dans ton composer.json, tu dois avoir une ligne `"files": [ "vendor/webforce3/w/W/globals.php" ]`

Retire là, puis un composer update pour prendre les modifs en compte.

Comme tu as fait ton projet avant la correction, le composer.json ne s'est probablement pas mis à jour.

**Comment by Moldjuice** [comment]
Impec, c'est réglé après la modif de composer.json et le retrait de cette ligne. 

Je vais procéder à l'update sur la version prod du projet. 

Merci beaucoup pour ton intervention. 

;-)

**Comment by Moldjuice** [comment]
Après maj du projet en prod et test, il semble que le problème de l'entête http en 404 ne soit pas résolu.
Si tu veux tester les projets avec W c'est sur [Outiref](https://www.outiref.fr). 
Les pages intérieures sont maintenant concernées par ce même souci, alors que seulement l'accueil l'était sur la versions précédente de W.

Le .htaccess au sein de public semble être le même.
